# 색인/슬라이스 기초

In [1]:
# numpy는 데이터 복사를 따로 하지 않는 이상 데이터가 복사되지 않음
# 데이터를 복사하기 위해서는 [:]로 슬라이스 해야함. 

In [3]:
import numpy as np

In [4]:
array = np.arange(10)

In [5]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array[3:8] = 10

In [7]:
array

array([ 0,  1,  2, 10, 10, 10, 10, 10,  8,  9])

In [8]:
array_slice = array[3:8]

In [9]:
array_slice

array([10, 10, 10, 10, 10])

In [10]:
array_slice[1] = 100

In [11]:
array_slice

array([ 10, 100,  10,  10,  10])

In [12]:
array #array_slice는 복사된것이 아니라 array를 참조한것(즉, 연결되어 있어 변경하면 array도 같이 변경됨)

array([  0,   1,   2,  10, 100,  10,  10,  10,   8,   9])

In [13]:
array_slice[:] = 99 #원소 전체를 의미한다.

In [14]:
array_slice

array([99, 99, 99, 99, 99])

In [15]:
array

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9])

# ndarray 전치 (transpose)

In [16]:
array1 = np.arange(32).reshape(2,4,4)

In [17]:
array1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [19]:
array1.shape

(2, 4, 4)

In [20]:
transpose_array = array1.transpose((1,0,2))
#axis1 = 2
#axis0 = 4
#axis2 = 4
#따라서 shape는 (4,2,4)로 될것임, 이거는 3이상의 다차원배열에서 이렇게 됨
#2차원 배열은 선형대수의 전치: 행과열을 바꾼다라는 의미

In [21]:
transpose_array

array([[[ 0,  1,  2,  3],
        [16, 17, 18, 19]],

       [[ 4,  5,  6,  7],
        [20, 21, 22, 23]],

       [[ 8,  9, 10, 11],
        [24, 25, 26, 27]],

       [[12, 13, 14, 15],
        [28, 29, 30, 31]]])

# 유니버셜 메소드

In [22]:
array2 = np.arange(10)

In [23]:
array3 = np.arange(10,20)

In [24]:
np.power(array2,array3) #밑을 array2로 하고 지수를 array3으로 

array([          0,           1,        4096,     1594323,   268435456,
         452807053,  -683606016, -2094633337,           0,  -400556711],
      dtype=int32)